### PR TITLE
adds Uniprot retrieve and parse to get gene, transcript, protein ids

### PR DESCRIPTION
**Pull request by anilthanki**

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @anilthanki, is this similar to: https://github.com/bgruening/galaxytools/tree/master/tools/uniprot_rest_interface

**Comment by anilthanki** [comment]
Hi @bgruening 

Looks like, Yours has more option than this, This just gives you results of Ensembl ids of Gene, Transcript and Protein, for input of UniProt result in txt format.

Anil

**Comment by nsoranzo** [comment]
@anilthanki Should we close this?

**Comment by anilthanki** [comment]
Yes that one is working.

**Pull request closed without merging**
