### PR TITLE
Update t_coffee to version 13.45.0.4846264

### PR DESCRIPTION
**Pull request by nsoranzo**
This replaces the `t_coffee` conda package (which used precompiled binaries and bundled methods) with the `t-coffee` one (which is compiled from source and uses other conda packages for methods).

This will fix https://help.galaxyproject.org/t/tcoffee-run-finishes-with-empty-results/3836 thanks to https://github.com/bioconda/bioconda-recipes/pull/25932 .

@anilthanki Can you test that all methods we expose in the tool UI still work? We may have to drop some of them, or add conda packages to the run requirements of the `t-coffee` conda package.

### CODE REVIEW

**Comment by anilthanki** [comment]
Tested it locally... 

Works with and wothout filter options...

However, `sap_pair` in **Pairwise Structual Method**, throws warning saying its not installed, and uses `TMalign` instead.

And `pcma_msa` in **Multiple Sequence Alignment Methods** is not installed by defaults and ends up failing the analysis.

Also `score_ascii`, `msf_aln` and `clustalw_aln` output format doenst open withing Galaxy, but they downloads.

**Comment by nsoranzo** [comment]
> Tested it locally...

Thanks for testing!

> However, `sap_pair` in **Pairwise Structual Method**, throws warning saying its not installed, and uses `TMalign` instead.

https://github.com/bioconda/bioconda-recipes/pull/26079
https://github.com/bioconda/bioconda-recipes/pull/26092
  
> Also `score_ascii`, `msf_aln` and `clustalw_aln` output format doesn't open withing Galaxy, but they downloads.

That's not connected to this PR, but we should change the `format` attributes of these `<data/>` elements to more general Galaxy datatypes (or added the datatypes to Galaxy, if it makes sense).

**Comment by nsoranzo** [comment]
> And `pcma_msa` in **Multiple Sequence Alignment Methods** is not installed by defaults and ends up failing the analysis.

[PCMA](http://prodata.swmed.edu/pcma/pcma.php) is not FOSS (non-commercial only), so we need to remove it. There's a huge list of other methods that should work and we could add, if there's interest.

**Comment by nsoranzo** [comment]
> That's not connected to this PR, but we should change the `format` attributes of these `<data/>` elements to more general Galaxy datatypes (or added the datatypes to Galaxy, if it makes sense).

Corrected 3 output formats in commit 1358948d12cf0338d5a057ccd37b43e02f9d2676 , opened PR to add the missing `msf` datatype to Galaxy 21.01 in https://github.com/galaxyproject/galaxy/pull/11084 .

I've removed the `amap_msa` method (AMAP has been retired by its authors: http://pachterlab.github.io/software.html ) and added a few other methods more or less randomly from the long list of available ones.

There are 4 more methods that are failing among those exposed in the previous version:
- [x] `kalign_msa`: missing run requirement in the t-coffee bioconda package https://github.com/bioconda/bioconda-recipes/pull/26183
- [x] `probcons_msa`: missing dependency [probconsRNA](http://probcons.stanford.edu/), I will try to add it to bioconda https://github.com/bioconda/bioconda-recipes/pull/26172
- [x] `dialigntx_msa`, `poa_msa`: these need certain files in `$MCOFFEE_4_TCOFFEE` directory, I will fix the `t-coffee` bioconda package https://github.com/bioconda/bioconda-recipes/pull/26183

**Pull request merged**
